---
- name: Add the packages in sources lists
  command: apt install apt-transport-https lsb-release software-properties-common ca-certificates -y
   
- name: Add the packages in sources lists  
  command: add-apt-repository ppa:ondrej/php -y
