---
# tasks file for /etc/ansible/roles/composer
- name: Download php-composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: install curl
  apt:
    name: curl
    state: present

- name: Download Composer Installer
  command: curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.p>

- name: Verify Installation Script is Safe to Run
  command: php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"


- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
   

#- name: make composer executable
#  file: 
#    path: /usr/local/bin/composer
#    mode: a+x
#    state: directory
    

- name: Remove phar
  file:
    path: composer.phar
    state: absent

- name: Remove Install Script
  file:
    path: /tmp/composer-setup.php
    state: absent
